--extensions 
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- init tables
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
GRANT ALL PRIVILEGES ON ALL TABLES in SCHEMA public TO traffic_user
GRANT ALL PRIVILEGES ON ALL SEQUENCES in SCHEMA public to traffic_user